[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "sc-big"
version = "0.1.0"
description = "Bayesian model for somatic SNV re-detection in single-cell DNA sequencing using bulk sequencing data"
authors = [{name = "Daniel Schütte"}]
maintainers = [{name = "Daniel Schütte"}]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.0.0",
    "matplotlib>=3.7.0",
    "scipy>=1.10.0",
    "torch>=2.0.0",
    "pyro-ppl>=1.8.0",
    "pysam>=0.22.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "pytest_xdist>=3.8.0",
    "flake8>=6.0.0",
]

[project.scripts]
sc-big = "scripts.snv_caller:main"

[tool.setuptools.packages.find]
where = ["."]
include = ["src*", "scripts*"]
